// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_EventSpawnerMZ","status":false,"description":"(v.1.2) Spawn events from a specified spawn map to a desired location.","parameters":{"mId":"0"}}
];
